import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const files=['index.html','word-unscrambler/index.html','word-finder/index.html','anagram-solver/index.html','5-letter-anagram-solver/index.html','6-letter-anagram-solver/index.html','7-letter-anagram-solver/index.html','word-unscrambler-uk/index.html','free-word-unscrambler/index.html'].map(file=>path.join(root,file));
const oldNav='<nav><a href="/word-unscrambler/">Unscrambler</a><a href="/word-finder/">Word Finder</a><a href="/anagram-solver/">Anagram Solver</a><a href="/word-lists/">Word Lists</a></nav>';
const newNav='<nav><a href="/word-unscrambler/">Unscrambler</a><a href="/wordle-solver/">Wordle Solver</a><a href="/crossword-solver/">Crossword Solver</a><a href="/word-lists/">Word Lists</a></nav>';
const oldSearch=/<div class="search"><input id="letters" class="letters" maxlength="20" placeholder="enter letters, e\.g\. stare"><button id="go">UNSCRAMBLE<\/button><\/div>/g;
const newSearch='<div class="search"><input id="letters" class="letters" maxlength="15" autocomplete="off" aria-label="Letters to unscramble" placeholder="enter letters, e.g. stare"><button id="go">FIND WORDS</button></div><div class="quick-actions"><button id="shuffle" class="secondary" type="button">Shuffle letters</button><button id="clear" class="secondary" type="button">Clear</button><button id="share-search" class="secondary" type="button">Share search</button></div><div class="examples"><span class="muted">Try:</span><button class="example" data-example="stare">STARE</button><button class="example" data-example="listen">LISTEN</button><button class="example" data-example="qu?tz">QU?TZ</button></div><div class="dictionary-row"><label for="dictionary">Word list</label><select id="dictionary" class="dictionary"><option value="broad">Broad English · 194k words</option><option value="common">Common-use English · 19k words</option></select></div>';
for(const file of files){let html=fs.readFileSync(file,'utf8');html=html.replace(oldNav,newNav).replace(oldSearch,newSearch).replace(/<meta name="twitter:card" content="summary">/g,'<meta name="twitter:card" content="summary_large_image"><meta property="og:image" content="https://wordunscramble.eu/social-card.svg"><meta name="twitter:image" content="https://wordunscramble.eu/social-card.svg">');fs.writeFileSync(file,html)}
console.log(`Upgraded ${files.length} pages`);
